### ISSUE TITLE
My validator does not appear in BigDipper

### ISSUE THREAD

**Issue by lightiv** [forbole/big-dipper#481]
**Describe the bug**

My validator does not appear in BigDipper: https://akash.bigdipper.live/validators/inactive 

**To Reproduce**
Currently, I am not in the active set so it should be appearing in the inactive.  I don't know if it matters but this validator was create with the '--ledger' option.  Also, I changed the moniker within 24 hrs of the upgrade so I know it is good.  Thanks.

```
akash query staking validator akashvaloper1zfcmwh56kmz4wqqg2t8pxrm228dx2c6hzh0ewm

commission:
  commission_rates:
    max_change_rate: "0.010000000000000000"
    max_rate: "0.200000000000000000"
    rate: "0.100000000000000000"
  update_time: "2021-02-20T01:16:02.583171722Z"
consensus_pubkey:
  '@type': /cosmos.crypto.ed25519.PubKey
  key: tDO1a8uwYo8osKuVS+PqGmuD8ZueL0j7KONR+PULID8=
delegator_shares: "1000000.000000000000000000"
description:
  details: As a pre-mainnet community validator and moderator, we support the Akash
    Network Decentralized Ecosystem and Marketplace.  Long live the Akash Cloud Cat!
  identity: 1510797E867F484E
  moniker: SkyNet | Validators
  security_contact: skynet@paullovette.com
  website: https://skynet.paullovette.com/
jailed: false
min_self_delegation: "1"
operator_address: akashvaloper1zfcmwh56kmz4wqqg2t8pxrm228dx2c6hzh0ewm
status: BOND_STATUS_UNBONDED
tokens: "1000000"
unbonding_height: "0"
unbonding_time: "1970-01-01T00:00:00Z"
```
